# Generated by Django 3.2.6 on 2021-09-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default_profile_pic.png", upload_to="profile_pics"
            ),
        ),
    ]
