# Generated by Django 3.2.6 on 2021-09-24 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order_codes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game_logs", "0011_gamedemo_gamefile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyBabyCodes",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("status", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "image1",
                    models.ImageField(
                        blank=True, upload_to=order_codes.models.MyBabyCodes.upload_path
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, upload_to=order_codes.models.MyBabyCodes.upload_path
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, upload_to=order_codes.models.MyBabyCodes.upload_path
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True, upload_to=order_codes.models.MyBabyCodes.upload_path
                    ),
                ),
                (
                    "image5",
                    models.ImageField(
                        blank=True, upload_to=order_codes.models.MyBabyCodes.upload_path
                    ),
                ),
                (
                    "image6",
                    models.ImageField(
                        blank=True, upload_to=order_codes.models.MyBabyCodes.upload_path
                    ),
                ),
                (
                    "image7",
                    models.ImageField(
                        blank=True, upload_to=order_codes.models.MyBabyCodes.upload_path
                    ),
                ),
                (
                    "image8",
                    models.ImageField(
                        blank=True, upload_to=order_codes.models.MyBabyCodes.upload_path
                    ),
                ),
                (
                    "image9",
                    models.ImageField(
                        blank=True, upload_to=order_codes.models.MyBabyCodes.upload_path
                    ),
                ),
                (
                    "image10",
                    models.ImageField(
                        blank=True, upload_to=order_codes.models.MyBabyCodes.upload_path
                    ),
                ),
                ("gamefile", models.FileField(blank=True, upload_to="")),
                (
                    "game_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_logs.gamedemo",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
