# Generated by Django 3.2.6 on 2021-10-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order_codes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mybabycodes",
            name="status",
        ),
    ]
