# Generated by Django 3.2.6 on 2021-10-16 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211016_1317'),
        ('order_codes', '0002_remove_mybabycodes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybabycodes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.guest'),
        ),
    ]
