# Generated by Django 3.2.6 on 2021-10-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_subject", models.CharField(max_length=255)),
                ("contact_message", models.TextField()),
            ],
        ),
    ]
