# Generated by Django 3.2.6 on 2021-09-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_logs", "0002_alter_gamedemo_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamedemo",
            name="image",
            field=models.ImageField(
                default="default_game_pic.jpg", upload_to="game_logs"
            ),
        ),
    ]
