# Generated by Django 3.2.6 on 2021-09-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_logs", "0004_auto_20210904_0630"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyBabyCodes",
        ),
    ]
