# Generated by Django 3.2.6 on 2021-09-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_logs", "0005_delete_mybabycodes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamedemo",
            old_name="image",
            new_name="display_image",
        ),
    ]
