# Generated by Django 3.2.6 on 2021-09-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_logs", "0006_rename_image_gamedemo_display_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedemo",
            name="character0",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="character1",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="character2",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="character3",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="character4",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="character5",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="character6",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="character7",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="character8",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="character9",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="number_of_characters",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
