# Generated by Django 3.2.6 on 2021-09-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_logs", "0007_auto_20210905_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedemo",
            name="user_img0",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="user_img1",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="user_img2",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="user_img3",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="user_img4",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="user_img5",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="user_img6",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="user_img7",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="user_img8",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="user_img9",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
    ]
