# Generated by Django 3.2.6 on 2021-09-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_logs", "0008_auto_20210905_1525"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedemo",
            name="example_image1",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="example_image2",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="example_image3",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
        migrations.AddField(
            model_name="gamedemo",
            name="example_image4",
            field=models.ImageField(null=True, upload_to="game_logs"),
        ),
    ]
