# Generated by Django 3.2.6 on 2021-09-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_logs", "0009_auto_20210905_1527"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamedemo",
            name="character0",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="character1",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="character2",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="character3",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="character4",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="character5",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="character6",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="character7",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="character8",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="character9",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="example_image1",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="example_image2",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="example_image3",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="example_image4",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="user_img0",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="user_img1",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="user_img2",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="user_img3",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="user_img4",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="user_img5",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="user_img6",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="user_img7",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="user_img8",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="user_img9",
            field=models.ImageField(blank=True, null=True, upload_to="game_logs"),
        ),
    ]
