# Generated by Django 3.2.6 on 2021-09-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_logs", "0010_auto_20210905_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedemo",
            name="gamefile",
            field=models.FileField(blank=True, upload_to="game_logs"),
        ),
    ]
