# Generated by Django 3.2.6 on 2021-09-26 23:46

from django.db import migrations, models
import game_logs.models


class Migration(migrations.Migration):

    dependencies = [
        ("game_logs", "0012_auto_20210925_1230"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamecharacter",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="gamedemo",
            options={"ordering": ["date_added"]},
        ),
        migrations.AddField(
            model_name="gamecharacter",
            name="height",
            field=models.PositiveSmallIntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamecharacter",
            name="width",
            field=models.PositiveSmallIntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gamedemo",
            name="gamefile",
            field=models.FileField(
                blank=True, upload_to=game_logs.models.GameDemo.game_directory_path
            ),
        ),
    ]
