# Generated by Django 3.2.6 on 2021-10-01 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order_drawings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game_logs", "0014_gamecharacter_orderimage_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MyBabyDrawings",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("status", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        upload_to=order_drawings.models.MyBabyDrawings.upload_path,
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        upload_to=order_drawings.models.MyBabyDrawings.upload_path,
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        upload_to=order_drawings.models.MyBabyDrawings.upload_path,
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True,
                        upload_to=order_drawings.models.MyBabyDrawings.upload_path,
                    ),
                ),
                (
                    "image5",
                    models.ImageField(
                        blank=True,
                        upload_to=order_drawings.models.MyBabyDrawings.upload_path,
                    ),
                ),
                (
                    "image6",
                    models.ImageField(
                        blank=True,
                        upload_to=order_drawings.models.MyBabyDrawings.upload_path,
                    ),
                ),
                (
                    "image7",
                    models.ImageField(
                        blank=True,
                        upload_to=order_drawings.models.MyBabyDrawings.upload_path,
                    ),
                ),
                (
                    "image8",
                    models.ImageField(
                        blank=True,
                        upload_to=order_drawings.models.MyBabyDrawings.upload_path,
                    ),
                ),
                (
                    "image9",
                    models.ImageField(
                        blank=True,
                        upload_to=order_drawings.models.MyBabyDrawings.upload_path,
                    ),
                ),
                (
                    "image10",
                    models.ImageField(
                        blank=True,
                        upload_to=order_drawings.models.MyBabyDrawings.upload_path,
                    ),
                ),
                ("gamefile", models.FileField(blank=True, upload_to="")),
                (
                    "game_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_logs.gamedemo",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
